### ISSUE TITLE
[Critical] JS-files don't seem to load properly

### ISSUE THREAD

**Issue by Martijn1981** [splittingred/TinyMCE#42]
I've just updated my TinyMCE version and there's a pretty critical bug present now. Whenever I'm publishing new pages, a lot of JS-files connected to the TinyMCE plugin don't seem to load properly. The result is non-formatted text!

Here's the error, pasted from the Webdeveloper toolbar in FF:

Fout: uncaught exception: [Exception... "String contains an invalid character"  code: "5" nsresult: "0x80530005 (NS_ERROR_DOM_INVALID_CHARACTER_ERR)"  location: "http://www.enadvies.nl/assets/components/tinymce/jscripts/tiny_mce/tiny_mce.js?v=208pl Line: 1"]

**Comment by splittingred** [comment]
Fixed in 4.2.0-rc2. Try that and get back to me.

**Comment by Martijn1981** [comment]
Nope, the same problem is still present. The Javascript errors only occur when NOTHING has been typed in the TinyMCE textfield yet, by the way, So it only happens with a completely empty. untouched textfield.
