### ISSUE TITLE
very bad js performance in different browsers

### ISSUE THREAD

**Issue by anselmh** [splittingred/TinyMCE#44]
In some browsers the live edit doesn' t work properly due to JS performance I think. text input is delayed up to 2sec (to see it in TinyMCE).
It works not in:
- Win / Mac Opera 11 (very fast JS engine)
- Win / Mac Firefox 3.6
- Win IE (9 not tested)
  but works in: (UPDATE: IS NOT WORKING IN ANY BROWSER CORRECTLY)
- Mac Safari 5
- Mac / Win Chrome (9+10beta)
- Win / Mac Firefox 4beta12

Firebug / Webinspector does only output a unspecified issue for tinyMCE which has been auto-fixed in browser.js

Environments:
- MODX Revo 2.0.8pl trad.
- TinyMCE 4.2.0rc2 (4.1.x has the same issues)
- browsers above
- OS X (10.6.6 / i5,8GB RAM) / Win XP Pro (i5 / 1GB RAM) but in all others too. Tested from several pcs and users.

---

JS errors in IE:
    tiny_mce.js?v=208 line 1 character 128567: 'undefined' is NULL or no object

It doesn't appear in TinyMCE standalone. Any suggestions?
Clients often use IE or Firefox 3.6 where it hass very bad performance… =/

**Comment by Martijn1981** [comment]
I have the same problems yeah. I've already notified Splittingred

**Comment by splittingred** [comment]
Fixed; was an issue with the forced_root_block setting. Fix is in 4.2.0-pl.

**Comment by anselmh** [comment]
It actually isn't fixed. I've got these performance lacks in every major browser (even google chrome 11).

While writing long texts (as a long blog entry) I recognize performance lacks in typing<->seeingwhatstyped. It isn't synchronized and some times it takes about 5secs to see what are my last 3 words I typed.

Thank you for getting into that.

**Comment by anselmh** [comment]
This issue is still not "closed". It appears in IE and even in Chrome/Opera/FF on older machines.
