### ISSUE TITLE
TinyMCE and newspublisher

### ISSUE THREAD

**Issue by jalz** [splittingred/TinyMCE#45]
Hi, Im using the newspublisher front end editor (created by BobRay) and it seems that the buttons in TinyMCE do not work. I found a small hack for version 4.12 which Bruno17 released for buttons but the drop down list for styles dont work. v4.20 would be cool if the buttons worked.....

**Comment by splittingred** [comment]
Done in 4.2.1-pl

**Comment by jalz** [comment]
Thanks splittingred, indded the buttons work :) however the styles drop down is still not working. Anychance you can fix this please?
